name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@master
    -
      name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    -
      name: Install testsuite
      run: pip install pytest
    -
      name: Run tests
      run: pytest
