name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@master
    -
      name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    -
      name: Install test suite
      run: pip install pytest
    -
      name: Run tests
      run: pytest -v
